In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import sklearn
import seaborn as sns
import os
import re

In [2]:
os.chdir('../')
os.getcwd()

'C:\\Users\\lgorman\\OneDrive\\Desktop\\PhD\\Analysis'

In [3]:
data=pd.read_csv(os.path.join('data',"processed","point_data_processed.csv")) # at this point we only preserve the grid geometry. Will need to add point geometry when reading the file back in again (same with country boundaries)

In [4]:
world_bank_development_indicators=pd.read_csv(os.path.join("data","world_development_indicators","WDIData.csv"), low_memory=False)
world_bank_development_indicators_metadata=pd.read_csv(os.path.join("data","world_development_indicators","WDICountry.csv"), low_memory=False)

In [5]:
all_world_bank_countrys=world_bank_development_indicators_metadata["Country Code"]

In [6]:
# Three letter country code from RHoMIS
data["Three_Letter_Country_Code"]="NaN"
for row in data.index:
    world_bank_row_with_rhomis_two_letter_code=world_bank_development_indicators_metadata["2-alpha code"]==data.loc[row,"ID_COUNTRY"]
    data.loc[row,"Three_Letter_Country_Code"]=world_bank_development_indicators_metadata.loc[world_bank_row_with_rhomis_two_letter_code,"Country Code"].to_list()[0] #need the to list object to extract the object

In [7]:
# subsetting world bank indicators only for data countries
world_bank_development_indicators=world_bank_development_indicators.loc[world_bank_development_indicators["Country Code"].isin(data["Three_Letter_Country_Code"].unique()),:]

In [8]:
all_indicators=world_bank_development_indicators["Indicator Code"].unique()
all_indicators=["COUNTRY_LEVEL_"+indicator for indicator in all_indicators]
empty_matrix=np.zeros((data.shape[0],len(all_indicators)))
country_level_indicators=pd.DataFrame(empty_matrix, columns=all_indicators)
data_with_country_level_indicators=pd.concat([data,country_level_indicators],axis=1)

In [102]:
data_with_country_level_indicators=data_with_country_level_indicators.drop(columns="Unnamed: 0")
data_with_country_level_indicators.columns

Index(['ID_PROJ', 'ID_COUNTRY', 'YEAR', 'ITERATION', 'SURVEY_ID', 'ID_HH',
       'GPS_LAT', 'GPS_LON', 'GPS_ALT', 'Country',
       ...
       'COUNTRY_LEVEL_SG.DMK.ALLD.FN.ZS', 'COUNTRY_LEVEL_SG.VAW.REAS.ZS',
       'COUNTRY_LEVEL_SG.VAW.ARGU.ZS', 'COUNTRY_LEVEL_SG.VAW.BURN.ZS',
       'COUNTRY_LEVEL_SG.VAW.GOES.ZS', 'COUNTRY_LEVEL_SG.VAW.NEGL.ZS',
       'COUNTRY_LEVEL_SG.VAW.REFU.ZS', 'COUNTRY_LEVEL_SP.M15.2024.FE.ZS',
       'COUNTRY_LEVEL_SP.M18.2024.FE.ZS', 'COUNTRY_LEVEL_SH.DYN.AIDS.FE.ZS'],
      dtype='object', length=1504)

In [ ]:
def isNaN(num):
    return num != num

#---------------------Creating empty data frame of world bank indicators ------------------------#
test_string="COUNTRY_LEVEL_SG.DMK.ALLD.FN.ZS"
test_pattern='COUNTRY_LEVEL_'


pattern_for_country_level_variables='COUNTRY_LEVEL_'
all_indicators=world_bank_development_indicators["Indicator Code"].unique()
all_indicators=["COUNTRY_LEVEL_"+indicator for indicator in all_indicators]
empty_matrix=np.empty((len(data["YEAR"].unique())*len(data["Three_Letter_Country_Code"].unique()),(2+len(all_indicators))))
empty_matrix[:]=np.nan #filling the array with nan values to populate
column_names=["Three_Letter_Country_Code", "YEAR"]
[column_names.append(indicator) for indicator in all_indicators]
country_level_indicators=pd.DataFrame(empty_matrix, columns=column_names)
unique_countries=pd.Series(data["Three_Letter_Country_Code"].unique())
unique_year=pd.Series(data["YEAR"].unique())

#-------------------Filling data frame with potential year and country values -------------------#
for country_index in unique_countries.index:
    for year_index in unique_year.index:
        row_number_in_new= year_index+country_index*len(unique_year)
        country_level_indicators.loc[row_number_in_new,"Three_Letter_Country_Code"]=unique_countries[country_index]
        country_level_indicators.loc[row_number_in_new,"YEAR"]=int(unique_year[year_index])

#-------------------Filling data frame with potential year and country values -------------------#

for country in country_level_indicators["Three_Letter_Country_Code"].unique():
    #indicator_temp=world_bank_development_indicators.loc[world_bank_development_indicators["Country Code"]==country_temp,:]
    for year in country_level_indicators["YEAR"].unique():
        #print (str(country)+str(int(year)))
        for column in all_indicators:
            if re.search(pattern_for_country_level_variables,column) is not None:
                temp_indicator=column.replace(test_pattern,'')
                subset1=country_level_indicators["Three_Letter_Country_Code"]==country 
                subset2=country_level_indicators["YEAR"]==year
                subset_world_bank_by_indicator=world_bank_development_indicators["Indicator Code"]==temp_indicator
                subset_world_bank_by_country=world_bank_development_indicators["Country Code"]==country
                
                year_temp=int(year)
                indicator_value_temp=float(world_bank_development_indicators.loc[subset_world_bank_by_indicator & subset_world_bank_by_country==True, str(int(year_temp))])
                if isNaN(indicator_value_temp)==False:
                    country_level_indicators.loc[subset1 & subset2==True,country_level_indicators.columns==column]=indicator_value_temp
                else:
                    while (isNaN(indicator_value_temp)==True & year_temp>2014):
                        year_temp=year_temp-1
                        indicator_value_temp=float(world_bank_development_indicators.loc[subset_world_bank_by_indicator & subset_world_bank_by_country==True, str(int(year_temp))])
                        country_level_indicators.loc[subset1 & subset2==True,country_level_indicators.columns==column]=indicator_value_temp

#--------------------------------Testing ------------------------------------------

test_pattern="COUNTRY_LEVEL_"
column="COUNTRY_LEVEL_EG.ELC.ACCS.ZS"
country="KEN"
year=2018.0


temp_indicator=column.replace(test_pattern,'')
subset1=country_level_indicators["Three_Letter_Country_Code"]==country 
subset2=country_level_indicators["YEAR"]==year
subset_world_bank_by_indicator=world_bank_development_indicators["Indicator Code"]==temp_indicator
subset_world_bank_by_country=world_bank_development_indicators["Country Code"]==country

year_temp=int(year)
indicator_value_temp=float(world_bank_development_indicators.loc[subset_world_bank_by_indicator & subset_world_bank_by_country==True, str(int(year_temp))])
indicator_value_temp

if isNaN(indicator_value_temp)==False:
    country_level_indicators.loc[subset1 & subset2==True,country_level_indicators.columns==column]=indicator_value_temp
else:
    while (isNaN(indicator_value_temp)==True & year_temp>2014):
        year_temp=year_temp-1
        indicator_value_temp=float(world_bank_development_indicators.loc[subset_world_bank_by_indicator & subset_world_bank_by_country==True, str(int(year_temp))])
        country_level_indicators.loc[subset1 & subset2==True,country_level_indicators.columns==column]=indicator_value_temp
        print(indicator_value_temp)

indicator_value_temp
country_level_indicators.loc[subset1 & subset2==True,country_level_indicators.columns==column]=indicator_value_temp
country_level_indicators.loc[subset1 & subset2==True,country_level_indicators.columns==column]

In [86]:
country_level_indicators.head()

,Three_Letter_Country_Code,YEAR,COUNTRY_LEVEL_PA.NUS.PPP.05,COUNTRY_LEVEL_PA.NUS.PRVT.PP.05,COUNTRY_LEVEL_EG.CFT.ACCS.ZS,COUNTRY_LEVEL_EG.ELC.ACCS.ZS,COUNTRY_LEVEL_EG.ELC.ACCS.RU.ZS,COUNTRY_LEVEL_EG.ELC.ACCS.UR.ZS,COUNTRY_LEVEL_FX.OWN.TOTL.ZS,COUNTRY_LEVEL_FX.OWN.TOTL.FE.ZS,...,COUNTRY_LEVEL_SG.DMK.ALLD.FN.ZS,COUNTRY_LEVEL_SG.VAW.REAS.ZS,COUNTRY_LEVEL_SG.VAW.ARGU.ZS,COUNTRY_LEVEL_SG.VAW.BURN.ZS,COUNTRY_LEVEL_SG.VAW.GOES.ZS,COUNTRY_LEVEL_SG.VAW.NEGL.ZS,COUNTRY_LEVEL_SG.VAW.REFU.ZS,COUNTRY_LEVEL_SP.M15.2024.FE.ZS,COUNTRY_LEVEL_SP.M18.2024.FE.ZS,COUNTRY_LEVEL_SH.DYN.AIDS.FE.ZS
0,KEN,2016.0,NaN,NaN,13.42,65.40000,61.090087,77.600000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.6
1,KEN,2017.0,NaN,NaN,NaN,63.81147,57.570480,81.066414,81.567566,77.746368,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.8
2,KEN,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.0
3,KEN,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TZA,2016.0,NaN,NaN,2.16,32.80000,17.270680,65.300000,NaN,NaN,...,35.2,58.0,42.0,20.2,40.9,47.9,30.5,5.2,30.5,60.0

In [87]:
data.head()

,Unnamed: 0,ID_PROJ,ID_COUNTRY,YEAR,ITERATION,SURVEY_ID,ID_HH,GPS_LAT,GPS_LON,GPS_ALT,...,raster_level_governance,raster_level_population_density,raster_level_institutional_capital,raster_level_AEZ,raster_level_time_to_market_20_k,raster_level_time_to_market_50_k,raster_level_time_to_market_100_k,raster_level_time_to_market_250_k,raster_level_time_to_market_500_k,Three_Letter_Country_Code
0,0,CM1,KE,2016,1,KE_CM1_2016,KE_2016_CM1_1_1,-1.82,37.70,1079.98,...,0.354685,111.778312,0.194244,312.0,0.869047,3.154210,3.244542,3.244542,3.244542,KEN
1,1,CM1,KE,2016,1,KE_CM1_2016,KE_2016_CM1_2_1,-1.82,37.70,1059.82,...,0.354685,111.778312,0.194244,312.0,0.869047,3.154210,3.244542,3.244542,3.244542,KEN
2,2,CM1,KE,2016,1,KE_CM1_2016,KE_2016_CM1_3_1,-1.82,37.71,1052.39,...,0.354685,111.497736,0.195894,312.0,0.890017,3.167381,3.270332,3.270332,3.270332,KEN
3,3,CM1,KE,2016,1,KE_CM1_2016,KE_2016_CM1_4_1,-1.82,37.70,1121.40,...,0.354685,111.778312,0.194244,312.0,0.869047,3.154210,3.244542,3.244542,3.244542,KEN
4,4,CM1,KE,2016,1,KE_CM1_2016,KE_2016_CM1_5_1,-1.82,37.70,1082.84,...,0.354685,111.778312,0.194244,312.0,0.869047,3.154210,3.244542,3.244542,3.244542,KEN

In [102]:
data["country_year"]=data["Three_Letter_Country_Code"]+"_"+data["YEAR"].astype(str)

country_level_indicators["country_year"]=country_level_indicators["Three_Letter_Country_Code"]+"_"+country_level_indicators["YEAR"].astype(int).astype(str)

In [105]:
merge_wb_and_rhomis=pd.merge(data,country_level_indicators, on="country_year")
merge_wb_and_rhomis.to_csv(os.path.join("data", "processed", "rhomis_points_with_country_level.csv"))